#!/usr/bin/env -S uv run --quiet --with pyyaml python3
"""Regenerate the derived parts of this repo from activity frontmatter:

  * README.md's activity tables (between the GENERATED markers)
  * ilo-coverage.md
  * in every activities/LA??/README.md: the "**Related ILOs:** …" header line, and
    hyperlinks on every bare ILO id in the body (frontmatter is left as plain data)

Usage:  python3 scripts/build-index.py            # rewrite files
        python3 scripts/build-index.py --check    # exit 1 if files are stale or ids invalid

Canonical data: activities/LA??/README.md (YAML frontmatter). ILO ids are validated
against ../intended-learning-outcomes/ilos.yaml when that checkout exists.
Runs via uv (shebang) which provisions PyYAML; or `python3 scripts/build-index.py` with PyYAML installed.
"""
import re, sys, pathlib, yaml

ROOT = pathlib.Path(__file__).resolve().parent.parent
ACT = ROOT / "activities"
ILO_YAML = ROOT.parent / "intended-learning-outcomes" / "ilos.yaml"
ILO_REPO = "https://github.com/iticse26-wg11/intended-learning-outcomes"
ILO_URL = ILO_REPO + "/blob/main/ilos/{id}.md"
BEGIN, END = "<!-- BEGIN GENERATED -->", "<!-- END GENERATED -->"
FM_RE = re.compile(r"---\n(.*?)\n---\n", re.S)
ID_RE = r"(?:H|MM|EPR|CS)\d{2}[a-z]?"
# existing markdown links and inline code are left alone; bare ids get linked
TOKEN_RE = re.compile(r"\[[^\]]*\]\([^)]*\)|`[^`]*`|\b(" + ID_RE + r")\b")
RELATED_RE = re.compile(r"^\*\*Related ILOs:\*\*.*$", re.M)

def load():
    acts = []
    for d in sorted(ACT.glob("LA[0-9][0-9]")):
        text = (d / "README.md").read_text()
        m = FM_RE.match(text)
        fm = yaml.safe_load(m.group(1))
        if fm["id"] != d.name:
            sys.exit(f"{d}/README.md: frontmatter id {fm['id']} != directory {d.name}")
        fm["_path"], fm["_fm"], fm["_body"] = d / "README.md", text[:m.end()], text[m.end():]
        acts.append(fm)
    return acts

def ilo_order():
    if not ILO_YAML.exists():
        return None
    y = yaml.safe_load(ILO_YAML.read_text())
    return [i["id"] for i in y["ilos"]], {a["id"]: a["name"] for a in y["areas"]}

def link(a):
    return f"[{a['id']}](activities/{a['id']}/README.md)"

def ilo_link(i):
    return f"[{i}]({ILO_URL.format(id=i)})"

def ilo_links(ids):
    return ", ".join(ilo_link(i) for i in ids)

def activity_readme(a):
    """Frontmatter untouched; header line regenerated; bare ILO ids in the body linked."""
    header = f"**Related ILOs:** {ilo_links(a['related_ilos'])}"
    if a.get("prerequisite_ilos"):
        header += f" · **Prerequisite ILOs:** {ilo_links(a['prerequisite_ilos'])}"
    body, n = RELATED_RE.subn(lambda m: header, a["_body"], count=1)
    if n == 0:
        sys.exit(f"{a['_path']}: no '**Related ILOs:**' line to regenerate")
    body = TOKEN_RE.sub(lambda m: ilo_link(m.group(1)) if m.group(1) else m.group(0), body)
    return a["_fm"] + body

def readme_block(acts, ilos):
    out = [f"{len(acts)} activities. IDs (`LA01`–`LA{len(acts):02d}`) follow the presentation order of the "
           "working-group report and are permanent: never renumbered or reused. "
           f"ILO ids link to their stable pages in [`intended-learning-outcomes`]({ILO_REPO}).", "",
           "| ID | Activity | Related ILOs | Type | Duration |", "|----|----------|--------------|------|----------|"]
    for a in acts:
        out.append(f"| {a['id']} | [{a['title']}](activities/{a['id']}/README.md) | "
                   f"{ilo_links(a['related_ilos'])} | {a['type']} | {a['duration']} |")
    if ilos:
        order, areas = ilos
        out += ["", "### By ILO area", "", "| Area | Activities |", "|------|------------|"]
        for pref, name in areas.items():
            ids = [a["id"] for a in acts if any(re.match(pref + r"\d", i) for i in a["related_ilos"])]
            out.append(f"| {name} ({pref}) | {', '.join(ids)} |")
    out += ["", "### By mode", "", "| Mode | Activities |", "|------|------------|"]
    for mode in ["Unplugged", "Digital", "Offline", None]:
        ids = [a["id"] for a in acts if a.get("mode") == mode]
        out.append(f"| {mode or 'Not specified (paper or digital)'} | {', '.join(ids)} |")
    return "\n".join(out)

def coverage(acts, ilos):
    rev = {}
    for a in acts:
        for i in a["related_ilos"]:
            rev.setdefault(i, []).append(a)
    order = ilos[0] if ilos else sorted(rev)
    missing = [i for i in order if i not in rev]
    used = set(rev) | {i for a in acts for i in a.get("prerequisite_ilos") or []}
    unknown = sorted(used - set(order)) if ilos else []
    out = ["# ILO coverage", "",
           "Which learning activities address which intended learning outcomes. Generated by "
           "`scripts/build-index.py` from the `related_ilos` field of each activity's frontmatter; "
           f"ILO ids come from [`ilos.yaml`]({ILO_REPO}/blob/main/ilos.yaml) in the "
           f"[`intended-learning-outcomes`]({ILO_REPO}) repository and link to each ILO's stable page.", ""]
    n_multi = sum(1 for i in rev.values() if len(i) > 1)
    out.append(f"**Summary:** {len(order) - len(missing)} of {len(order)} ILOs are covered"
               + (f"; uncovered: {', '.join(missing)}" if missing else "")
               + (f"; {n_multi} ILOs are addressed by more than one activity." if n_multi else "; each covered ILO is addressed by exactly one activity."))
    if unknown:
        out.append(f"\n**Unknown ILO ids in activities:** {', '.join(unknown)}")
    out += ["", "## ILO → activities", "", "| ILO | Activities |", "|-----|------------|"]
    for i in order:
        out.append(f"| {ilo_link(i)} | {', '.join(link(a) for a in rev.get(i, [])) or '—'} |")
    out += ["", "## Activity → ILOs", "", "| Activity | Related ILOs | Prerequisite ILOs |", "|----------|--------------|-------------------|"]
    for a in acts:
        pre = ilo_links(a.get("prerequisite_ilos") or []) or "—"
        out.append(f"| {link(a)} {a['title']} | {ilo_links(a['related_ilos'])} | {pre} |")
    return "\n".join(out) + "\n", unknown

def main():
    check = "--check" in sys.argv
    acts, ilos = load(), ilo_order()
    readme = ROOT / "README.md"
    txt = readme.read_text()
    pre, _, rest = txt.partition(BEGIN)
    _, _, post = rest.partition(END)
    files = {readme: f"{pre}{BEGIN}\n{readme_block(acts, ilos)}\n{END}{post}"}
    files[ROOT / "ilo-coverage.md"], unknown = coverage(acts, ilos)
    for a in acts:
        files[a["_path"]] = activity_readme(a)
    if unknown:
        print("unknown ILO ids:", ", ".join(unknown))
    stale = [p for p, s in files.items() if p.read_text() != s]
    if check:
        for p in stale: print("stale:", p.relative_to(ROOT))
        sys.exit(1 if stale or unknown else 0)
    for p in stale:
        p.write_text(files[p])
    print(f"wrote {len(stale)} file(s):", ", ".join(str(p.relative_to(ROOT)) for p in stale) or "nothing stale")

main()
