#!/usr/bin/env -S uv run --quiet --with pyyaml python3
"""Regenerate README.md's activity tables and ilo-coverage.md from activity frontmatter.

Usage:  python3 scripts/build-index.py            # rewrite files
        python3 scripts/build-index.py --check    # exit 1 if files are stale or ids invalid

Canonical data: activities/LA??/README.md (YAML frontmatter). ILO ids are validated
against ../intended-learning-outcomes/ilos.yaml when that checkout exists.
Runs via uv (shebang) which provisions PyYAML; or `python3 scripts/build-index.py` with PyYAML installed.
"""
import re, sys, pathlib, yaml

ROOT = pathlib.Path(__file__).resolve().parent.parent
ACT = ROOT / "activities"
ILO_YAML = ROOT.parent / "intended-learning-outcomes" / "ilos.yaml"
BEGIN, END = "<!-- BEGIN GENERATED -->", "<!-- END GENERATED -->"

def load():
    acts = []
    for d in sorted(ACT.glob("LA[0-9][0-9]")):
        text = (d / "README.md").read_text()
        m = re.match(r"---\n(.*?)\n---\n", text, re.S)
        fm = yaml.safe_load(m.group(1))
        if fm["id"] != d.name:
            sys.exit(f"{d}/README.md: frontmatter id {fm['id']} != directory {d.name}")
        acts.append(fm)
    return acts

def ilo_order():
    if not ILO_YAML.exists():
        return None
    y = yaml.safe_load(ILO_YAML.read_text())
    return [i["id"] for i in y["ilos"]], {a["id"]: a["name"] for a in y["areas"]}

def link(a):
    return f"[{a['id']}](activities/{a['id']}/README.md)"

def readme_block(acts, ilos):
    out = [f"{len(acts)} activities. IDs (`LA01`–`LA{len(acts):02d}`) follow the presentation order of the "
           "working-group report and are permanent: never renumbered or reused.", "",
           "| ID | Activity | Related ILOs | Type | Duration |", "|----|----------|--------------|------|----------|"]
    for a in acts:
        out.append(f"| {a['id']} | [{a['title']}](activities/{a['id']}/README.md) | "
                   f"{', '.join(a['related_ilos'])} | {a['type']} | {a['duration']} |")
    if ilos:
        order, areas = ilos
        out += ["", "### By ILO area", "", "| Area | Activities |", "|------|------------|"]
        for pref, name in areas.items():
            ids = [a["id"] for a in acts if any(re.match(pref + r"\d", i) for i in a["related_ilos"])]
            out.append(f"| {name} ({pref}) | {', '.join(ids)} |")
    out += ["", "### By mode", "", "| Mode | Activities |", "|------|------------|"]
    for mode in ["Unplugged", "Digital", "Offline", None]:
        ids = [a["id"] for a in acts if a.get("mode") == mode]
        out.append(f"| {mode or 'Not specified (paper or digital)'} | {', '.join(ids)} |")
    return "\n".join(out)

def coverage(acts, ilos):
    rev = {}
    for a in acts:
        for i in a["related_ilos"]:
            rev.setdefault(i, []).append(a)
    order = ilos[0] if ilos else sorted(rev)
    missing = [i for i in order if i not in rev]
    unknown = sorted(set(rev) - set(order)) if ilos else []
    out = ["# ILO coverage", "",
           "Which learning activities address which intended learning outcomes. Generated by "
           "`scripts/build-index.py` from the `related_ilos` field of each activity's frontmatter; "
           "ILO ids come from [`../intended-learning-outcomes/ilos.yaml`](../intended-learning-outcomes/ilos.yaml).", ""]
    n_multi = sum(1 for i in rev.values() if len(i) > 1)
    out.append(f"**Summary:** {len(order) - len(missing)} of {len(order)} ILOs are covered"
               + (f"; uncovered: {', '.join(missing)}" if missing else "")
               + (f"; {n_multi} ILOs are addressed by more than one activity." if n_multi else "; each covered ILO is addressed by exactly one activity."))
    if unknown:
        out.append(f"\n**Unknown ILO ids in activities:** {', '.join(unknown)}")
    out += ["", "## ILO → activities", "", "| ILO | Activities |", "|-----|------------|"]
    for i in order:
        out.append(f"| {i} | {', '.join(link(a) for a in rev.get(i, [])) or '—'} |")
    out += ["", "## Activity → ILOs", "", "| Activity | Related ILOs | Prerequisite ILOs |", "|----------|--------------|-------------------|"]
    for a in acts:
        pre = ", ".join(a.get("prerequisite_ilos") or []) or "—"
        out.append(f"| {link(a)} {a['title']} | {', '.join(a['related_ilos'])} | {pre} |")
    return "\n".join(out) + "\n", unknown

def main():
    check = "--check" in sys.argv
    acts, ilos = load(), ilo_order()
    readme = ROOT / "README.md"
    txt = readme.read_text()
    pre, _, rest = txt.partition(BEGIN)
    _, _, post = rest.partition(END)
    new_readme = f"{pre}{BEGIN}\n{readme_block(acts, ilos)}\n{END}{post}"
    new_cov, unknown = coverage(acts, ilos)
    if unknown:
        print("unknown ILO ids:", ", ".join(unknown))
    stale = [p for p, s in [(readme, new_readme), (ROOT / "ilo-coverage.md", new_cov)] if p.read_text() != s]
    if check:
        for p in stale: print("stale:", p.relative_to(ROOT))
        sys.exit(1 if stale or unknown else 0)
    readme.write_text(new_readme)
    (ROOT / "ilo-coverage.md").write_text(new_cov)
    print("wrote README.md, ilo-coverage.md")

main()
